name: JSON Message Log Validation

on:
  push:
    paths:
      - "messages.json"

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate JSON Structure
        uses: limitusus/jsonschema-validator-action@v1
        with:
          file: messages.json
          schema: schema.json
